### ISSUE TITLE
Decorator Creates to many quotes

### ISSUE THREAD

**Issue by maetthu-indermuehle** [vshn/puppet-gitlab#36]
Hiera Code:
```
gitlab::gitlab_rails:
  omniauth_enabled: true
  omniauth_allow_single_sign_on: false
  block_auto_created_users: true
  omniauth_providers:
    - name: "github"
      app_id: "9a6161e2354332d5b5f5"
      app_secret: "ec032383e83fb59205a381f3ac9ec98a9a2bb486"
      url: "https://github.com/"
      args:
       scope: "user:email"
```

The result in /etc/gitlab/gitlab.rb
```
gitlab_rails['omniauth_providers'] = ["{"name"=>"github", "app_id"=>"9a6161e2354332d5b5f5", "app_secret"=>"ec032383e83fb59205a381f3ac9ec98a9a2bb486", "url"=>"https://github.com/", "args"=>{"scope"=>"user:email"}}"]
```

The quote in the Array is not needed.
